---
version: "3.8"
services:
  movies:
    image: kiranchamala/projectmovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: kiranchamala/projecttrain:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: kiranchamala/projectrecharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: kiranchamala/projectdth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
